---
repos:
#  - repo: https://github.com/adrienverge/yamllint.git
#    rev: v1.32.0
#    hooks:
#      - id: yamllint
#        args:
#          - -c=.config/yamllint.yaml
#          - --strict
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: pretty-format-json
        args:
          - '--autofix'
      - id: check-yaml
      - id: check-symlinks
      - id: check-added-large-files
        args: ['--maxkb=3000']
      - id: detect-aws-credentials
        args:
          - '--allow-missing-credentials'
      - id: detect-private-key
      - id: no-commit-to-branch
      - id: forbid-submodules
      - id: check-vcs-permalinks
