creation_rules:
  # sandbox environment
  - path_regex: secrets.*\.us-east-1.*.tfvars.*.json$
    kms: arn:aws:kms:us-east-1:732758452413:key/00fbbabe-fdea-4fea-91aa-d52dbf5f62e5

sops:
  kms:
    - arn: arn:aws:kms:us-east-1:732758452413:key/00fbbabe-fdea-4fea-91aa-d52dbf5f62e5

stores:
  json:
    indent: 2
  json_binary:
    indent: 2
