creation_rules:
  # Sandbox environment
  - path_regex: fixtures.sandbox.tfvars.*$
    kms: arn:aws:kms:us-east-1:732758452413:key/00fbbabe-fdea-4fea-91aa-d52dbf5f62e5
  - path_regex: secrets.sandbox.auto.tfvars.*$
    kms: arn:aws:kms:us-east-1:732758452413:key/00fbbabe-fdea-4fea-91aa-d52dbf5f62e5
