---
# This workflow is brought to you by Flufi LLC and is licensed under the MIT License. (c) 2024 Flufi LLC.
# All rights reserved.
# Please note that Flufi LLC owns the original version of this workflow,
# which can be found at https://github.com/flufi-io/workflows. Thank you for using our workflows!

# This action initializes Terraform in directories up to three levels deep containing *.tf files

name: 'Terraform Init'
description: 'Initialize Terraform in directories up to three levels deep containing *.tf files'
author: 'Flufi LLC'
inputs:
  path:
    description: 'Path to start searching for .tf files'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Find directories with .tf files and run terraform init
      id: terraform-init
      shell: bash
      run: |
        directories=$(find ${{ inputs.path }} -maxdepth 3 -type f -name '*.tf' -exec dirname {} \; | sort | uniq)
        if [ -z "$directories" ]; then
          echo "No directories with *.tf files found."
          exit 0
        fi
        directories=$(echo $directories | tr ' ' '\n')
        echo "Terraform init will be run in the following directories:"
        echo $directories
        for dir in $directories; do
          echo "Running terraform init in $dir"
          (cd "$dir" && terraform init -lock=false -upgrade -reconfigure)
        done
