---
# This workflow is brought to you by Flufi LLC and is licensed under the MIT License. (c) 2024 Flufi LLC.
# All rights reserved.
# Please note that Flufi LLC owns the original version of this workflow,
# which can be found at https://github.com/flufi-io/workflows. Thank you for using our workflows!

# This actions runs pre-commit checks on Terraform files,
# and it will use the cache to speed up the process on subsequent runs for the installed hooks.

name: 'Pre-commit Terraform'
description: 'Run pre-commit checks on Terraform files'
author: 'Flufi LLC'
inputs:
  path:
    description: 'Path to start searching for .tf files'
    required: false
    default: '.'
  extra_args:
    description: 'Extra arguments to pass to pre-commit'
    required: false
    default: ''


runs:
  using: 'composite'
  steps:
    - name: Restore pre-commit cache
      id: cache-pre-commit-restore
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pre-commit-

    - name: Install pre-commit hooks
      shell: bash
      run: |
        echo "Installing pre-commit hooks..."
        pre-commit install --install-hooks

    - name: Run pre-commit checks
      run: pre-commit run --show-diff-on-failure --color=always --all-files ${{ inputs.extra_args }}
      shell: bash

    - name: Save pre-commit cache
      id: cache-pre-commit-save
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
        save-always: true
