---
# This workflow is brought to you by Flufi LLC and is licensed under the MIT License. (c) 2023 Flufi LLC.
# All rights reserved.
# Please note that Flufi LLC owns the original version of this workflow,
# which can be found at https://github.com/flufi-io/workflows. Thank you for using our workflows!

name: docker-build
on:
  pull_request:

permissions:
  contents: write
  packages: write

jobs:
  service:
    uses: ./.github/workflows/docker_build.yaml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
