---
# This workflow is brought to you by Flufi LLC and is licensed under the MIT License. (c) 2024 Flufi LLC.
# All rights reserved.
# Please note that Flufi LLC owns the original version of this workflow,
# which can be found at https://github.com/flufi-io/workflows. Thank you for using our workflows!

name: Post valid Terraform commands on new PR
on:
  workflow_call:
    outputs:
      environments:
        description: "A comma-separated list of available environments"
        value: ${{ jobs.post_valid_commands.outputs.environments }}

permissions:
  contents: read
  issues: write

jobs:
  post_valid_commands:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch environments
        id: fetch-environments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          env_list=$(gh api repos/${{ github.repository }}/environments \
            --header "Accept: application/vnd.github+json" \
            | jq -r '.environments[].name' | paste -sd "," -)
          echo "environments=$env_list" >> $GITHUB_ENV
          echo "environments=$env_list" >> $GITHUB_OUTPUT

      - name: Post comment
        run: |
          pr_number="${{ github.event.pull_request.number }}"
          comment_body="This is a comment posted by a GitHub Action."

          comment_data='{"body": "'"${comment_body//\"/\\\"}"'"}'
          curl --request POST \
            --url "https://api.github.com/repos/${{ github.repository }}/issues/${pr_number}/comments" \
            --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --header 'content-type: application/json' \
            --data "$comment_data"
