---
# This workflow is brought to you by Flufi LLC and is licensed under the MIT License. (c) 2024 Flufi LLC.
# All rights reserved.
# Please note that Flufi LLC owns the original version of this workflow,
# which can be found at https://github.com/flufi-io/workflows. Thank you for using our workflows!

name: Post valid Terraform commands on new PR
on:
  workflow_call:
    outputs:
      environments:
        description: "A comma-separated list of available environments"
        value: ${{ jobs.post_valid_commands.outputs.environments }}

permissions:
  contents: read
  issues: write

jobs:
  post_valid_commands:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Fetch environments
        id: fetch-environments
        continue-on-error: false
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: |
          env_list=$(gh api repos/${{ github.repository }}/environments \
            --header "Accept: application/vnd.github+json" \
            | jq -r '.environments[].name' | paste -sd "," -)
          echo "environments=$env_list" >> $GITHUB_ENV
          echo "environments=$env_list" >> $GITHUB_OUTPUT

      - name: Post comment with valid commands
        continue-on-error: false
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: |
          pr_number="${{ github.event.number }}"
          valid_commands="Valid commands for this repository are:\n\n"
          for environment in $(echo "${{ steps.fetch-environments.outputs.environments }}" | tr ',' ' '); do
            valid_commands+="\`/terraform plan ${environment}\`\n"
            valid_commands+="\`/terraform apply ${environment}\`\n"
          done

          echo "$valid_commands" | gh pr comment "$pr_number" --repo ${{ github.repository }} --body-file=-
