name: Post valid Terraform commands on PR
on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  post_commands:
    uses:  flufi-io/workflows/.github/workflows/post_valid_tf_commands.yaml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
