name: Post valid Terraform commands on new PR
on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
    outputs:
      environments:
        description: "A comma-separated list of available environments"
        value: ${{ jobs.post_valid_commands.outputs.environments }}

jobs:
  post_valid_commands:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch environments
        id: fetch-environments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          env_list=$(gh api repos/${{ github.repository }}/environments \
            --header "Accept: application/vnd.github+json" \
            | jq -r '.environments[].name' | paste -sd "," -)
          echo "environments=$env_list" >> $GITHUB_ENV
          echo "environments=$env_list" >> $GITHUB_OUTPUT

      - name: Post comment with valid commands
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number="${{ github.event.number }}"
          valid_commands="Valid commands for this repository are:\n\n"
          valid_commands+="* /terraform plan [environment]\n"
          valid_commands+="* /terraform apply [environment]\n\n"
          valid_commands+="Available environments: ${{ steps.fetch-environments.outputs.environments }}\n"

          comment_data='{"body": "'"${valid_commands//\"/\\\"}"'"}'
          curl --request POST \
            --url "https://api.github.com/repos/${{ github.repository }}/issues/${pr_number}/comments" \
            --header "authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
            --header 'content-type: application/json' \
            --data "$comment_data"
