---
# This workflow is brought to you by Flufi LLC and is licensed under the MIT License. (c) 2024 Flufi LLC.
# All rights reserved.
# Please note that Flufi LLC owns the original version of this workflow,
# which can be found at https://github.com/flufi-io/workflows. Thank you for using our workflows!

name: terratest

on:
  workflow_call:
    inputs:
      ref:
        description: 'Branch or commit to checkout'
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write
  id-token: write  # This is required to use the AWS Credentials

env:
  GH_TOKEN: ${{ secrets.github_token }}  # This is required to use the gh cli

jobs:
  terratest:
    runs-on: ubuntu-latest
    environment: sandbox
    container: ghcr.io/flufi-io/terraform-docker-action:latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          path: main

      - name: configure aws credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::732758452413:role/github-oidc
          aws-region: us-east-1

      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: main/tests/complete/go.mod
          go-version: '>=1.21.0'

      - name: setup tofu
        run: |
          tfenv use latest

      - name: run terratest
        id: terratest
        working-directory: main/tests/complete
        run: |
          export GOOS=linux GOARCH=amd64 CGO_ENABLED=0
          go mod tidy > /dev/null
          go test -v -count=1 -timeout 120m ./...
