name: Terraform Plan

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment that was extracted from the comment'
        required: true
        type: string
      operation:
        description: 'The operation that was extracted from the comment'
        required: true
        type: string
      varsfile:
        description: 'The path to the vars file'
        required: true
        type: string
      working-directory:
        description: 'The path to the working directory'
        required: false
        default: '.'
        type: string
      ref:
        description: 'The ref to checkout'
        required: true
        type: string

    outputs:
      artifact_name:
        description: 'The artifact that contains plan and cache'
        value: terraform-artifacts-${{ inputs.ref }}
      artifact_path:
        description: 'The path where the artifact is stored'
        value: artifacts-${{ inputs.ref }}.tar.gz


jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ref: refs/pull/${{ inputs.ref }}/head
          repository: ${{ github.repository }}
      - name: files
        run: |
          ls -la
          pwd

      - name: Terraform Init
        run: terraform init -input=false -no-color -upgrade -reconfigure
        working-directory: ${{ inputs.working-directory }}

      - name: Terraform Plan
        working-directory: ${{ inputs.working-directory }}
        run: terraform plan -out=tfplan -var-file=${{ inputs.varsfile }} -input=false -no-color

      - name: Save Terraform state and plan
        working-directory: ${{ inputs.working-directory }}
        id: save-artifact
        run: tar czf artifacts-${{ inputs.ref }}.tar.gz .terraform tfplan

      - name: install sops
        run: |
          wget https://github.com/mozilla/sops/releases/download/v3.7.3/sops_3.7.3_amd64.deb
          sudo dpkg -i sops_3.7.3_amd64.deb

      - name: encrypt terraform plan
        id: encrypt
        working-directory: ${{ inputs.working-directory }}
        run: |
          sops -e -i artifacts-${{ inputs.ref }}.tar.gz

      - name: Upload Terraform artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-artifacts-${{ inputs.ref }}
          path: ${{ inputs.working-directory }}/artifacts-${{ inputs.ref }}.tar.gz
          retention-days: 1
