---
# This workflow is brought to you by Flufi LLC and is licensed under the MIT License. (c) 2024 Flufi LLC.
# All rights reserved.
# Please note that Flufi LLC owns the original version of this workflow,
# which can be found at https://github.com/flufi-io/workflows. Thank you for using our workflows!

name: terraform-pre-commit

on:
  workflow_call:
    inputs:
      ref:
        description: 'Branch or commit to checkout'
        required: true
        type: string

permissions: write-all

env:
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.github_token }}

jobs:
  pre-commit:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: install pre-commit dependencies
        run: |
          brew install terraform-docs
          brew install pre-commit
          brew install trivy
          brew install checkov
          brew install tflint
          brew install tfenv
          brew install tfupdate

      - name: Run pre-commit checks
        run: |
          tfenv use latest
          pre-commit install --install-hooks
          pre-commit autoupdate &&  pre-commit run -a
