name: terraform
on:
  issue_comment:
    types: [ created ]
permissions: write-all
env:
  VALID_ENVIRONMENTS: development,staging,production


jobs:
  validate_comment:
    uses: flufi-io/workflows/.github/workflows/valid_comment.yaml@main
    with:
      valid_environments: development,staging,production
      comment_body: ${{ github.event.comment.body }}

  terraform_plan:
    if: ${{ needs.validate_comment.outputs.operation }} == 'plan'
    needs: [ validate_comment ]
    uses: flufi-io/workflows/.github/workflows/terraform_plan.yaml@main
    secrets: inherit
    with:
      environment: ${{ needs.validate_comment.outputs.environment }}
      operation: ${{ needs.validate_comment.outputs.operation }}
      varsfile: example.tfvars
      working-directory: terraform
      pr_number: ${{ needs.validate_comment.outputs.pr_number }}
      artifact_path: ${{ needs.validate_comment.outputs.artifact_path }}
      commit_sha: ${{ needs.validate_comment.outputs.commit_sha }}

  terraform_apply:
    if: ${{ needs.validate_comment.outputs.operation }} == 'apply'
    needs: [ validate_comment ]
    uses: flufi-io/workflows/.github/workflows/terraform_apply.yaml@main
    secrets: inherit
    with:
      working-directory: terraform
      environment: ${{ needs.validate_comment.outputs.environment }}
      operation: ${{ needs.validate_comment.outputs.operation }}
      pr_number: ${{ needs.validate_comment.outputs.pr_number }}
      artifact_path: ${{ needs.validate_comment.outputs.artifact_path }}
      commit_sha: ${{ needs.validate_comment.outputs.commit_sha }}
