name: terraform
on:
  issue_comment:
    types: [ created ]
permissions: write-all
env:
  VALID_ENVIRONMENTS: development,staging,production





jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.comment.sha }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.2
          terraform_wrapper: false

      - name: Get associated open pull request
        id: get_pr
        run: |
          pr_number=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/timeline?per_page=100" \
            | jq '.[] | select(.event=="referenced") | select(.source.issue.state=="open") | .commit_id' | head -1)
          echo "commit_sha=$pr_number" >> $GITHUB_OUTPUT

      - name: Display commit SHA
        run: |
          echo "Commit SHA: ${{ steps.get_pr.outputs.commit_sha }}"

  validate_comment:
    uses: flufi-io/workflows/.github/workflows/valid_comment.yaml@main
    with:
      valid_environments: development,staging,production
      comment_body: ${{ github.event.comment.body }}

  terraform_plan:
    uses: flufi-io/workflows/.github/workflows/terraform_plan.yaml@main
    with:
      environment: ${{ needs.validate_comment.outputs.environment }}
      operation: ${{ needs.validate_comment.outputs.operation }}
      varsfile: example.tfvars
      working-directory: terraform
      ref: ${{ github.event.comment.sha }}

  download_plan:
    runs-on: ubuntu-latest
    needs: [ terraform_plan ]
    steps:
      - name: Download Terraform artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{needs.terraform_plan.outputs.name}}
          path: ${{needs.terraform_plan.outputs.path}}
