---
# This workflow is brought to you by Flufi LLC and is licensed under the MIT License. (c) 2023 Flufi LLC.
# All rights reserved.
# Please note that Flufi LLC owns the original version of this workflow,
# which can be found at https://github.com/flufi-io/workflows. Thank you for using our workflows!

name: terratest

on:
  workflow_call:
    inputs:
      ref:
        description: 'Branch or commit to checkout'
        required: true
        type: string
      secrets:
        description: '1Password secret path'
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  terratest:
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          AWS_ROLE_ARN: op://flufi-sandbox/github_actions/AWS_ROLE_ARN
          AWS_REGION: op://flufi-sandbox/github_actions/AWS_REGION
          GITHUB_TOKEN: op://flufi-sandbox/github_actions/GITHUB_TOKEN

      - name: configure aws credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          path: main

      - uses: actions/setup-go@v4
        with:
          cache-dependency-path: main/tests/go.mod
          go-version: '>=1.21.0'

      - name: run terratest with 1Password secrets
        working-directory: main/tests
        run: |
          export GOOS=linux GOARCH=amd64 CGO_ENABLED=0
          go mod init test
          go mod tidy > /dev/null
          op run --env-file ../examples/complete/secrets.env -- go test -v -count=1 -timeout 120m ./...
