---
# This workflow is brought to you by Flufi LLC and is licensed under the MIT License. (c) 2024 Flufi LLC.
# All rights reserved.
# Please note that Flufi LLC owns the original version of this workflow,
# which can be found at https://github.com/flufi-io/workflows. Thank you for using our workflows!

name: terraform apply

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment that was extracted from the comment'
        required: true
        type: string
      operation:
        description: 'The operation that was extracted from the comment'
        required: true
        type: string
      working-directory:
        description: 'The path to the working directory'
        required: false
        default: '.'
        type: string
      repo:
        description: 'The repo that was extracted from the comment'
        required: true
        type: string
      pr_number:
        description: 'The PR number that was extracted from the comment'
        required: true
        type: string
      commit_sha:
        description: 'The commit sha that was extracted from the comment'
        required: true
        type: string
      artifact_name:
        description: 'The name of the artifact'
        required: true
        type: string
      terraform_version:
        required: false
        type: string
        default: ''
      env_vars:
        description: 'Multi-line string of environment variables to pass to the steps'
        required: false
        type: string
        default: ''

permissions:
  contents: read
  pull-requests: write
  id-token: write  # This is required to use the AWS Credentials

env:
  GH_TOKEN: ${{ secrets.github_token }}  # This is required to use the gh cli

jobs:
  terraform_apply:
    if: ${{ inputs.operation == 'apply' }}
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.setup.outputs.artifact }}
    steps:
      - name: Add link to workflow run in PR comment
        id: add_link_to_pr_comment
        run: |
          pr_number="${{ inputs.pr_number }}"
          link="https://github.com/${{ inputs.repo }}/actions/runs/${{ github.run_id }}"
          job_name="${{ github.job }}"
          comment="You can check the current run of the $job_name [here]($link)"
          curl --request POST \
            --url "https://api.github.com/repos/${{ github.repository }}/issues/${pr_number}/comments" \
            --header "authorization: Bearer ${{ secrets.github_token }}" \
            --header 'content-type: application/json' \
            --data "{\"body\": \"${comment}\"}"

      - name: setup
        id: setup
        run: |
          echo "artifact_name=${{ inputs.artifact_name }}" >> $GITHUB_OUTPUT
          echo "artifact=${{ inputs.working-directory }}/${{ inputs.artifact_name }}" >> $GITHUB_OUTPUT
          echo "${{ inputs.env_vars }}" | while read -r line
          do
            echo "$line" >> $GITHUB_ENV
          done

      - name: configure aws credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        id: setup-terraform
        with:
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
          terraform_version: ${{ inputs.terraform_version }}
          terraform_wrapper: false

      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ inputs.pr_number }}/head
          repository: ${{ inputs.repo }}

      - name: Download Terraform artifacts
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          search_artifacts: true
          name: ${{ steps.setup.outputs.artifact_name }}

      - name: Add PR comment if Download Terraform artifacts fails
        if: ${{ failure() && steps.download-artifact.outcome == 'failure' }}
        run: |
          comment_body="error: Failed to download Terraform artifacts. Please run a **terraform plan** before."
          comment_payload=$(jq -n --arg body "$comment_body" '{"body": $body}')
          gh issue comment "${{ inputs.pr_number }}" -r "${{ inputs.repo }}" -b "${comment_body}"
          exit 1
        continue-on-error: false

      - name: Get and Delete Artifacts
        id: get-and-delete-artifacts
        run: |
          artifact_name="${{ steps.setup.outputs.artifact_name }}"
          artifact_data=$(gh api repos/${{ inputs.repo }}/actions/artifacts)
          artifact_ids=$(echo "$artifact_data" | jq -r ".artifacts[] | select(.name == \"$artifact_name\") | .id")

          for artifact_id in $artifact_ids; do
            echo "Deleting artifact with ID: $artifact_id"
            gh api repos/${{ inputs.repo }}/actions/artifacts/$artifact_id -X DELETE
          done
        continue-on-error: false


      - name: install sops
        id: install-sops
        run: |
          wget https://github.com/mozilla/sops/releases/download/v3.8.0/sops_3.8.0_amd64.deb
          sudo dpkg -i sops_3.8.0_amd64.deb
        continue-on-error: false

      - name: decrypt plan
        run: |
          sops -d -i ${{ steps.setup.outputs.artifact_name }}
        continue-on-error: false

      - name: extract plan
        run: |
          tar xzf ${{ steps.setup.outputs.artifact_name }}
          rm ${{ steps.setup.outputs.artifact_name }}
        continue-on-error: false

      - name: terraform apply
        if: ${{ steps.check_approval.outputs.code_owner_approval == 'true' }}
        id: terraform_apply
        run: |
          terraform init -reconfigure -upgrade
          terraform  ${{ inputs.operation }} -input=false -no-color -auto-approve tfplan

        continue-on-error: false
        working-directory: ${{ inputs.working-directory }}

      - name: Post Terraform apply output as PR comment
        working-directory: ${{ inputs.working-directory }}
        run: |
          apply_output=$(cat apply_output.txt)
          max_comment_size=65535

          # Split the apply output into smaller chunks
          split_output=$(echo "$apply_output" | awk -v size="$max_comment_size" '{
            printf("%s%s",$0,RT)
            if (length > size) {
              print ""
              $0=$0
            }
          }')

          for chunk in "${split_output[@]}"; do
            comment_payload=$(jq -n --arg body "$chunk" '{"body": $body}')
            gh issue comment "${{ inputs.pr_number }}" -R "${{ inputs.repo }}" -b "$chunk"
          done
