name: terraform
on:
  issue_comment:
    types: [ created ]
permissions: write-all
env:
  VALID_ENVIRONMENTS: development,staging,production


jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.get_pr.outputs.commit_sha }}
      pr_number: ${{ steps.get_pr.outputs.pr_number }}
      repo: ${{ steps.get_pr.outputs.repo }}
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

  validate_comment:
    uses: flufi-io/workflows/.github/workflows/valid_comment.yaml@main
    with:
      valid_environments: development,staging,production
      comment_body: ${{ github.event.comment.body }}

  terraform_plan:
    needs: [ setup, validate_comment ]
    uses: flufi-io/workflows/.github/workflows/terraform_plan.yaml@main
    secrets: inherit
    with:
      environment: ${{ needs.validate_comment.outputs.environment }}
      operation: ${{ needs.validate_comment.outputs.operation }}
      varsfile: example.tfvars
      working-directory: terraform
      ref: ${{ needs.setup.outputs.commit_sha }}

  download_plan:
    runs-on: ubuntu-latest
    needs: [ terraform_plan ]
    steps:
      - name: Download Terraform artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{needs.terraform_plan.outputs.name}}
          path: ${{needs.terraform_plan.outputs.path}}
