---
# This workflow is brought to you by Flufi LLC and is licensed under the MIT License. (c) 2023 Flufi LLC.
# All rights reserved.
# Please note that Flufi LLC owns the original version of this workflow,
# which can be found at https://github.com/flufi-io/workflows. Thank you for using our workflows!

name: terraform-pre-commit

on:
  workflow_call:
    inputs:
      ref:
        description: 'Branch or commit to checkout'
        required: true
        type: string
      secrets_path:
        description: 'Path to the secrets file'
        required: false
        type: string

permissions:
  contents: read


env:
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.github_token }}

jobs:
  pre-commit:
    environment: sandbox
    runs-on: ubuntu-latest
    container: ghcr.io/flufi-io/flufi-cli:latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          path: main

      - name: Set up pre-commit hooks
        run: pre-commit install --install-hooks
        working-directory: main

      - name: Run pre-commit checks
        id: terraform_modules
        run: |
          find . -type f -name 'secrets.env' -print0 | xargs -0 -I {} op run --env-file {} -- pre-commit run -a
