---
name: terraform pre-commit test
on:
  pull_request:
permissions: write-all

jobs:
  pre-commit:
    uses: ./.github/workflows/terraform_precommit.yaml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
