---
# This workflow is brought to you by Flufi LLC and is licensed under the MIT License. (c) 2024 Flufi LLC.
# All rights reserved.
# Please note that Flufi LLC owns the original version of this workflow,
# which can be found at https://github.com/flufi-io/workflows. Thank you for using our workflows!

name: terraform-pre-commit

on:
  workflow_call:
    inputs:
      ref:
        description: 'Branch or commit to checkout'
        required: true
        type: string

permissions:
  contents: read

jobs:
  pre-commit:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: setup pre-commit dependencies
        uses: ./.github/actions/pre-commit-terraform-dependencies

      - name: terraform init
        uses: ./.github/actions/pre-commit-terraform-init
        with:
          path: ${{ github.workspace }}

      - name: Run pre-commit checks
        run: |
          pre-commit install --install-hooks
          pre-commit autoupdate &&  pre-commit run -a --verbose
