---
name: terraform-pre-commit

on:
  workflow_call:
    inputs:
      ref:
        description: 'Branch or commit to checkout'
        required: true
        type: string

permissions:
  contents: read
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container: ghcr.io/flufi-io/docker-terraform-action:latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ inputs.ref }}
          path: main

      - name: Set up pre-commit hooks
        run: pre-commit install --install-hooks
        working-directory: main

      - name: Run pre-commit checks
        run: pre-commit run -a
        working-directory: main
