name: terraform apply test
on:
  issue_comment:
    types: [ created ]
permissions: write-all

jobs:
  terraform_command_validation:
    uses: flufi-io/workflows/.github/workflows/valid_tf_command.yaml@main
    with:
      comment_body: ${{ github.event.comment.body }}

  terraform_plan:
    if: ${{ needs.terraform_command_validation.outputs.operation == 'plan' }}
    needs: [ terraform_command_validation ]
    uses: flufi-io/workflows/.github/workflows/terraform_plan.yaml@main
    with:
      environment: ${{ needs.terraform_command_validation.outputs.environment }}
      operation: ${{ needs.terraform_command_validation.outputs.operation }}
      working-directory: terraform
      artifact_name: ${{ needs.terraform_command_validation.outputs.artifact_name }}
      pr_number: ${{ needs.terraform_command_validation.outputs.pr_number }}
      commit_sha: ${{ needs.terraform_command_validation.outputs.commit_sha }}
      repo: ${{ needs.terraform_command_validation.outputs.repo }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OIDC_ROLE: ${{ secrets.OIDC_ROLE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_TOKEN: ${{ secrets.TF_TOKEN }} # Optional: You can omit this line if you don't use Terraform Cloud.

  terraform_apply:
    needs: [terraform_command_validation]
    if: ${{ needs.terraform_command_validation.outputs.operation == 'apply' }}
    uses: flufi-io/workflows/.github/workflows/terraform_apply.yaml@main
    with:
      environment: ${{ needs.terraform_command_validation.outputs.environment }}
      operation: ${{ needs.terraform_command_validation.outputs.operation }}
      working-directory: terraform
      artifact_name: ${{ needs.terraform_command_validation.outputs.artifact_name }}
      pr_number: ${{ needs.terraform_command_validation.outputs.pr_number }}
      commit_sha: ${{ needs.terraform_command_validation.outputs.commit_sha }}
      repo: ${{ needs.terraform_command_validation.outputs.repo }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OIDC_ROLE: ${{ secrets.OIDC_ROLE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_TOKEN: ${{ secrets.TF_TOKEN }} # Optional: You can omit this line if you don't use Terraform Cloud.
