---
# This workflow is brought to you by Flufi LLC and is licensed under the MIT License. (c) 2023 Flufi LLC.
# All rights reserved.
# Please note that Flufi LLC owns the original version of this workflow,
# which can be found at https://github.com/flufi-io/workflows. Thank you for using our workflows!

name: terratest

on:
  workflow_call:
    inputs:
      ref:
        description: 'Branch or commit to checkout'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  terratest:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::732758452413:role/github-oidc
          aws-region: us-east-1

      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          path: main

      - name: install sops
        run: |
          wget https://github.com/mozilla/sops/releases/download/v3.8.1/sops_3.8.1_amd64.deb
          sudo dpkg -i sops_3.8.1_amd64.deb

      - uses: actions/setup-go@v4
        with:
          cache-dependency-path: main/tests/go.mod
          go-version: '>=1.21.0'

      - name: run terratest
        working-directory: main/tests
        run: |
          export GOOS=linux GOARCH=amd64 CGO_ENABLED=0
          go mod init test
          go mod tidy > /dev/null
          go test -v -count=1 -timeout 120m ./...
