name: terraform command validation test
on:
  issue_comment:
    types: [ created ]
permissions:
  contents: read
  pull-requests: read

jobs:
  validate_command:
    uses: flufi-io/workflows/.github/workflows/valid_tf_command.yaml@main
    secrets: inherit
    with:
      comment_body: ${{ github.event.comment.body }}

  print_environment_and_operation:
    needs: [validate_command]
    runs-on: ubuntu-latest
    steps:
      - name: Print environment and operation
        run: |
          [[ "${{ github.event.comment.body }}" == "/terraform ${{needs.validate_command.outputs.operation}} ${{needs.validate_command.outputs.environment}}" ]]
        if: ${{ success() }}
