---
# This workflow is brought to you by Flufi LLC and is licensed under the MIT License. (c) 2023 Flufi LLC.
# All rights reserved.
# Please note that Flufi LLC owns the original version of this workflow,
# which can be found at https://github.com/flufi-io/workflows. Thank you for using our workflows!

name: terraform command validation
on:
  workflow_call:
    inputs:
      comment_body:
        description: 'The body of the comment that triggered the workflow'
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: false

    outputs:
      environment:
        description: 'The environment that was extracted from the comment'
        value: ${{ jobs.terraform_command_validation.outputs.environment }}
      operation:
        description: 'The operation that was extracted from the comment'
        value: ${{ jobs.terraform_command_validation.outputs.operation }}
      pr_number:
        description: 'The PR number that was extracted from the comment'
        value: ${{ jobs.terraform_command_validation.outputs.pr_number }}
      repo:
        description: 'The repo that was extracted from the comment'
        value: ${{ jobs.terraform_command_validation.outputs.repo }}
      commit_sha:
        description: 'The commit sha that was extracted from the comment'
        value: ${{ jobs.terraform_command_validation.outputs.commit_sha }}
      artifact_name:
        description: 'The path where the artifact is stored'
        value: ${{ jobs.terraform_command_validation.outputs.artifact_name }}
permissions: write-all

jobs:
  terraform_command_validation:
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.check_valid_command.outputs.valid }}
      operation: ${{ steps.set_environment.outputs.operation }}
      environment: ${{ steps.set_environment.outputs.environment }}
      pr_number: ${{ steps.get_pr.outputs.pr_number }}
      repo: ${{ steps.get_pr.outputs.repo }}
      commit_sha: ${{ steps.get_pr.outputs.commit_sha }}
      artifact_name: ${{ steps.set_environment.outputs.artifact_name }}
    steps:
      - name: Check if comment is from a Pull Request
        id: check_pr_comment
        run: |
          issue_url="${{ github.event.issue.url }}"
          pr_url=$(gh api "$issue_url" | jq -r '.pull_request.url')
          if [ "$pr_url" != "null" ]; then
            echo "pr_comment=true" >> $GITHUB_OUTPUT
          else
            echo "pr_comment=false" >> $GITHUB_OUTPUT
          fi

      - name: Get associated open pull request
        if: ${{ steps.check_pr_comment.outputs.pr_comment == 'true' }}
        id: get_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_data=$(gh api -X GET "/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}" \
            | jq 'select(.state == "open") | {number: .number, sha: .head.sha, repo: .head.repo.full_name}')

          pr_number=$(echo "$pr_data" | jq '.number')
          commit_sha=$(echo "$pr_data" | jq '.sha')
          repo=$(echo "$pr_data" | jq -r '.repo')

          echo "pr_number=$pr_number" >> $GITHUB_OUTPUT
          echo "commit_sha=$commit_sha" >> $GITHUB_OUTPUT
          echo "repo=$repo" >> $GITHUB_OUTPUT

      - name: Add link to workflow run in PR comment
        id: add_link_to_pr_comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.run_id }}
        run: |
          pr_number="${{ steps.get_pr.outputs.pr_number }}"
          link="https://github.com/${{ steps.get_pr.outputs.repo }}/actions/runs/${{ env.RUN_ID }}"
          job_name="${{ github.job }}"
          comment="You can check the current run of the $job_name [here]($link)"
          curl --request POST \
            --url "https://api.github.com/repos/${{ github.repository }}/issues/${pr_number}/comments" \
            --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --header 'content-type: application/json' \
            --data "{\"body\": \"${comment}\"}"



      - name: Check if valid command
        if: ${{ steps.check_pr_comment.outputs.pr_comment == 'true' }}
        id: check_valid_command
        run: |
          comment="${{ inputs.comment_body }}"
          if [[ ! "$comment" =~ ^/ ]]; then
            echo "Invalid command: comment must start with a slash"
            exit 0
          else
            comment="${comment#"/"}"
          fi
          if [[ "$comment" =~ ^\s ]]; then
            echo "Invalid command: comment cannot start with whitespace"
            exit 1
          fi
          if [[ "$comment" =~ [^[:alnum:][:space:]\.-]+$ ]]; then
            echo "Invalid command: comment can only end with alphanumeric characters, whitespace, '.', or '-'"
            exit 1
          fi
          num_words=$(echo "$comment" | wc -w)
          operation=$(echo "$comment" | awk '{print $1 " " $2}')
          environment=$(echo "$comment" | awk '{print $3}')
          if [ $num_words -eq 3 ] && ([ "$operation" == "terraform plan" ] || [ "$operation" == "terraform apply" ]) \
            && [[ "$environment" =~ ^[[:alnum:]]+$ ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "valid=false" >> $GITHUB_OUTPUT
            echo "Invalid command: Must be '/terraform [plan|apply] [environment]'."
            exit 1
          fi

      - name: check valid environment
        id: check_valid_environment
        run: |
          if [ "${{ steps.check_valid_command.outputs.valid }}" == "false" ]; then
            echo "Invalid command: Must be '/terraform [plan|apply] [environment]'."
            exit 1
          fi
          env_list=$(gh api repos/${{ github.repository }}/environments \
            --header "Accept: application/vnd.github+json" \
            | jq -r '.environments[].name')
          if [[ "$env_list" =~ (^|,)${environment}($|,) ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
            echo "environment=${environment}" >> $GITHUB_OUTPUT
          else
            echo "Invalid command: environment, '${environment}' does not exist in the repository, '$env_list'}'"
            exit 1
          fi

      - name: Extract environment and operation from command
        if: ${{ steps.check_pr_comment.outputs.pr_comment == 'true' }}
        id: set_environment
        run: |
          comment="${{ inputs.comment_body }}"
          export environment=$(echo "$comment" | awk '{print $3}')
          export operation=$(echo "$comment" | awk '{print $2}')
          export artifact_name="plan-${environment}-${{ steps.get_pr.outputs.commit_sha }}.tar.gz"

          echo "artifact_name=$artifact_name" >> $GITHUB_OUTPUT
          echo "environment=$environment" >> $GITHUB_OUTPUT
          echo "operation=$operation" >> $GITHUB_OUTPUT
