name: terraform
on:
  issue_comment:
    types: [ created ]
permissions: write-all
env:
  VALID_ENVIRONMENTS: development,staging,production

jobs:
  validate_comment:
    uses: flufi-io/workflows/.github/workflows/valid_comment.yaml@main
    with:
      valid_environments: development,staging,production
      comment_body: ${{ github.event.comment.body }}

  print_environment_and_operation:
    needs: [validate_comment]
    runs-on: ubuntu-latest
    steps:
      - name: Print environment and operation
        run: |
          [["${{ github.event.comment.body }}" == "terraform ${{needs.validate_comment.outputs.operation}} ${{needs.validate_comment.outputs.environment}}"]]
