# This workflow is brought to you by Flufi LLC and is licensed under the MIT License. (c) 2023 Flufi LLC. All rights reserved.
# Please note that Flufi LLC owns the original version of this workflow,
# which can be found at https://github.com/flufi-io/workflows. Thank you for using our workflows!

name: terraform command validation test
on:
  issue_comment:
    types: [ created ]
permissions:
  contents: read
  pull-requests: write
  issues: write


jobs:
  validate_command:
    uses: flufi-io/workflows/.github/workflows/valid_tf_command.yaml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      comment_body: ${{ github.event.comment.body }}

  print_environment_and_operation:
    needs: [validate_command]
    runs-on: ubuntu-latest
    steps:
      - name: Print environment and operation
        run: |
          [[ "${{ github.event.comment.body }}" == "/terraform ${{needs.validate_command.outputs.operation}} ${{needs.validate_command.outputs.environment}}" ]]
        if: ${{ success() }}
