---
# This workflow is brought to you by Flufi LLC and is licensed under the MIT License. (c) 2024 Flufi LLC.
# All rights reserved.
# Please note that Flufi LLC owns the original version of this workflow,
# which can be found at https://github.com/flufi-io/workflows. Thank you for using our workflows!

name: terraform command validation test
on:
  issue_comment:
    types: [ created ]

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform_command_validation:
    uses: ./.github/workflows/valid_tf_command.yaml
    secrets: inherit
    with:
      comment_body: ${{ github.event.comment.body }}

  print_environment_and_operation:
    needs: [terraform_command_validation]
    runs-on: ubuntu-latest
    steps:
      - name: Compare environment and operation are the same as the ones extracted from the comment
        # checkov:skip=CKV_GHA_2:Ensure run commands are not vulnerable to shell injection
        env:
          EXPECTED_COMMAND: >-
            - /terraform ${{needs.terraform_command_validation.outputs.operation}}
            - ${{needs.terraform_command_validation.outputs.environment}}
        run: |
          ACTUAL_COMMAND=$(echo "${{ github.event.comment.body }}" | sed 's/[^a-zA-Z0-9 ]//g')
          if [ "$ACTUAL_COMMAND" = "$EXPECTED_COMMAND" ]; then
            echo "The command matches the expected pattern."
          else
            echo "The command does not match the expected pattern."
            exit 1
          fi
